---
name: Test This Action without cache

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: ${{ matrix.package.name }}
    container:
      image: rocker/verse:4.1.2
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        package:
          - name: buckbeak
            report_pkg_dir: ./tests/packages/buckbeak
            report_template_path: ./tests/packages/buckbeak/validation-template.Rmd
            report_rmarkdown_format: html_document

    steps:
      - name: Checkout ${{ matrix.package.name }}
        uses: actions/checkout@v3

      - name: Generate validation report for ${{ matrix.package.name }}
        uses: ./
        id: validation
        with:
          report_pkg_dir: ${{ matrix.package.report_pkg_dir }}
          report_template_path: ${{ matrix.package.report_template_path }}
          report_output_prefix: validation_report
          report_rmarkdown_format: ${{ matrix.package.report_rmarkdown_format }}
          no_cache: true

      - name: Upload ${{ matrix.package.name }} validation report
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: ${{ matrix.package.name }} validation report
          path: ${{ steps.validation.outputs.report_output_filename }}
          if-no-files-found: error
