---
name: Test the validation pipeline reusable workflow

on:
  push:
    branches:
      - val-pipeline-mvp

jobs:
  test-val-pipeline-buckbeats:
    uses: ./.github/workflows/val-pipeline.yaml
    with:
      target: buckbeak
      report_pkg_dir: ./tests/packages/buckbeak
      report_template_path: ./tests/packages/buckbeak/validation-template.Rmd
      report_rmarkdown_format: html_document
      additional_tlmgr_packages: "courier ec"
